version: "3"

services:
  mysql:
    container_name: mysql-server
    image: mysql:8.0.32
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: todo4
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    ports:
      - "3306:3306"

  app:
    container_name: todo-app
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    ports:
      - 3030:3030
    depends_on:
      - mysql
    environment:
      - PORT=3030
      - MYSQL_DBNAME=todo4
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin1234
    volumes:
      - .:/app/delegated
      - /app/node_modules
